[
    "piz",
    [
        "pizza hut",
        "pizza delivery",
        "pizza time",
        "pizza hut menu",
        "pizza dough recipe",
        "pizza hut coupon",
        "pizza places near me",
        "pizza hut deals",
        "pizza hut super bowl deal",
        "pizza factory",
        "pizza pizzazz",
        "pizza dough",
        "pizza mart",
        "pizza pizazz",
        "pizza gallery",
        "pizza dip",
        "pizza bank",
        "pizza studio",
        "pizookie",
        "pizza sauce recipe"
    ],
    [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [ ],
    {
        "google:clientdata": {
            "bpc": false,
            "phi": 0,
            "tlw": false
        },
        "google:suggestrelevance": [
            1100,
            601,
            600,
            566,
            565,
            564,
            563,
            562,
            561,
            560,
            559,
            558,
            557,
            556,
            555,
            554,
            553,
            552,
            551,
            550
        ],
        "google:suggesttype": [
            "QUERY",
            "QUERY",
            "QUERY",
            "QUERY",
            "QUERY",
            "QUERY",
            "QUERY",
            "QUERY",
            "QUERY",
            "QUERY",
            "QUERY",
            "QUERY",
            "QUERY",
            "QUERY",
            "QUERY",
            "QUERY",
            "QUERY",
            "QUERY",
            "QUERY",
            "QUERY"
        ],
        "google:verbatimrelevance": 851
    }
]